###
### Stage 0 - Base: Install base packages needed for builder and runtime
###
FROM python:3.11-slim-bullseye AS base

WORKDIR /subgen

# Install required build & runtime dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    tzdata \
    && rm -rf /var/lib/apt/lists/*

# Handle timezone from $TZ docker variable
RUN ln -sf /usr/share/zoneinfo/$TZ /etc/timezone && \
    ln -sf /usr/share/zoneinfo/$TZ /etc/localtime

###
### Stage 1 - Builder: Install packages needed for builder only and build dependencies
###
FROM base AS builder

# Install only required build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements and install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir --prefix=/install torch torchaudio --extra-index-url https://download.pytorch.org/whl/cpu && pip install --no-cache-dir --prefix=/install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu

###
### Stage 2a - Runtime: Create a minimal runtime image
###
FROM base AS runtime

# Install only required runtime dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Copy necessary files from builder
COPY --from=builder /install /usr/local

###
### Stage 2b - Runtime: Load app source code and run app
###
FROM runtime AS runtime-app
# Copy application source code
COPY launcher.py \
     subgen.py \
     language_code.py \
     translator_ollama.py \
     .
# Set command to run the application
CMD ["python3", "launcher.py"]

