# Docker Compose file [GPU]



#-----------------------------------
# Desccription
#-----------------------------------
# 
# Multiples services
# ------------------
# 
# 4 docker services are used to run 4 instances of subgen :
# 
# - 1) subgen-transcribe   : Transcribe to audio language.	Uses built-in WhisperAI.
# - 2) subgen-translate-en : Translate to English.		Uses built-in WhisperAI.
# - 3) subgen-translate-mk : Translate to Macedonian.		Uses an external Ollama instance.
# - 4) subgen-translate-fr : Translate to French.		Uses an external Ollama instance.
# 
# Each subgen instance is linked to a specific Jellyfin webhook.
# Each webhook is then restricted to a specific Jellyfin user.
# 
# 
# 
# Scenario
# --------
# 
# On-demand subtitle generation set up for one native macedonian and one native french, both fluent in english.
# When a subtitle is wanted for a video, just log with the correct Jellyfin user and hit the play button to trigger subtitle generation.
# 
# Examples :
# - "I need my native language subtitles for this japanese anime" --> Use subtitle-translate-mk
# - "English subtitles are enough for this regular british TV show" --> Use subtitle-transcribe
# - "Let's learn Spanish with an Spanish video training" --> Use subtitle-transcribe
# - "Let's watch a Italian video together and settle for english subtitles" --> Use subtitle-translate-en
# 
# 
# 
# Overload
# --------
# 
# To limit concurrent tasks, at service scope, Subgen uses a queuing system.
# External Ollama instance can be configured to run only 1 LLM model at a time (not caring how many subgen services are using it in the same time).
# 
# If Ollama uses the same GPU than subgen (in a separate Docker container on the same host, for example), built-in WhisperAI from one service and Ollama instance triggered from another service could use GPU resources at the same time.
# 
# 
# 
# Multiples GPU
# -------------
# 
# On a multiple-GPU system, Docker extension fields are used here to target a unique GPU.
# Each service can then be anchored to a specific GPU.
# This avoids overload due to multiples services running on the same GPU at the same time.
# 
# On a single-GPU system, if using multiples services simultaneously, be ready to have enough GPU resources to support concurrent tasks.
# 
# By default, the 4 subgen services are set up to use the first GPU.
# To anchor a service to a different GPU, simply adapt the name of the anchor used in the the service (first line: "#<<: *subgen-gpuN", where 'N' is 0-3).
#
# 



#-----------------------------------
# Common service extension fields
#-----------------------------------
#
# This section is reused across different services.
# - Avoid pulling and build instead.
# - Fetch the image built.
# - Handle Nvidia GPU support.
#
# One extension field per GPU.
#
#
x-subgen-gpu0: &subgen-gpu0
  image: subgen:local
  pull_policy: never
  tty: true
  restart: unless-stopped
  runtime: nvidia
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            device_ids: ['0']		# Use only GPU with id '0'
            capabilities: [gpu]

x-subgen-gpu1: &subgen-gpu1
  image: subgen:local
  pull_policy: never
  tty: true
  restart: unless-stopped
  runtime: nvidia
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            device_ids: ['1']		# Use only GPU with id '1'
            capabilities: [gpu]

x-subgen-gpu2: &subgen-gpu2
  image: subgen:local
  pull_policy: never
  tty: true
  restart: unless-stopped
  runtime: nvidia
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            device_ids: ['2']		# Use only GPU with id '2'
            capabilities: [gpu]

x-subgen-gpu3: &subgen-gpu3
  image: subgen:local
  pull_policy: never
  tty: true
  restart: unless-stopped
  runtime: nvidia
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            device_ids: ['3']		# Use only GPU with id '3'
            capabilities: [gpu]



#-----------------------------------
# Common volumes extension fields
#-----------------------------------
#
# This section is reused across different services.
# - Use the docker volumes mapped to the CIFS shares.
#
#
x-shared-volumes: &shared-volumes
  - type: volume
    source: cifs-files-tv1
    target: /tv1
    volume:
      nocopy: true
  - type: volume
    source: cifs-files-tv2
    target: /tv2
    volume:
      nocopy: true
  - type: volume
    source: cifs-files-hd
    target: /hd
    volume:
      nocopy: true
  - type: volume
    source: cifs-files-sd
    target: /sd
    volume:
      nocopy: true
  - type: volume
    source: cifs-files-misc-subgen-models
    target: /subgen/models
    volume:
      nocopy: true



#-----------------------------------
# Services
#-----------------------------------
#
# This section defines the different services :
# - 1 service to build the image locally.
# - 4 services depending on the locally built image.
#
#
services:
  # Build the image once
  subgen-builder:
    build:
      context: .
      dockerfile: Dockerfile			# GPU build file
    image: subgen:local
    command: ["true"]				# exits with status 0

  # Transcribe on gpu0 with built-in Whisper AI model.
  subgen-transcribe:
    <<: *subgen-gpu0				# Use GPU 0
    container_name: subgen-transcribe
    depends_on:
      - subgen-builder
    volumes: *shared-volumes
    env_file:
      - path: ./subgen-gpu.env			# GPU only
        required: true
      - path: ./subgen-common.env		# Shared across services
        required: true
      - path: ./subgen-transcribe.env		# Unique to "subgen-transcribe" service
        required: true
    ports:
       - "9000:9000"

  # Translate on gpu1 to EN with built-in Whisper AI model.
  subgen-translate-en:
    #<<: *subgen-gpu1				# Use GPU 1
    <<: *subgen-gpu0				# Use GPU 0
    container_name: subgen-translate-en
    depends_on:
      - subgen-builder
    volumes: *shared-volumes
    env_file:
      - path: ./subgen-gpu.env			# GPU only
        required: true
      - path: ./subgen-common.env		# Shared across services
        required: true
      - path: ./subgen-translate-en.env		# Unique to "subgen-translate-en" service
        required: true
    ports:
       - "9001:9000"

  # Translate on gpu2 to MK with external Ollama instance.
  subgen-translate-mk:
    #<<: *subgen-gpu2				# Use GPU 2
    <<: *subgen-gpu0				# Use GPU 0
    container_name: subgen-translate-mk
    depends_on:
      - subgen-builder
    volumes: *shared-volumes
    env_file:
      - path: ./subgen-gpu.env			# GPU only
        required: true
      - path: ./subgen-common.env		# Shared across services
        required: true
      - path: ./subgen-translate-mk.env		# Unique to "subgen-translate-mk" service
        required: true
    ports:
       - "9002:9000"

  # Translate on gpu3 to FR with external Ollama instance.
  subgen-translate-fr:
    #<<: *subgen-gpu3				# Use GPU 3
    <<: *subgen-gpu0				# Use GPU 0
    container_name: subgen-translate-fr
    depends_on:
      - subgen-builder
    volumes: *shared-volumes
    env_file:
      - path: ./subgen-gpu.env			# GPU only
        required: true
      - path: ./subgen-common.env		# Shared across services
        required: true
      - path: ./subgen-translate-fr.env		# Unique to "subgen-translate-fr" service
        required: true
    ports:
       - "9003:9000"



#-----------------------------------
# Volumes
#-----------------------------------
#
# This section maps the CIFS shares to docker volumes.
#
# Defines variables in "./.env" file.
#
#
volumes:
  cifs-files-tv1:
    driver: local
    driver_opts:
      type: cifs
      o: username=${NAS_USER},password=${NAS_PASS},uid=${NAS_UID},gid=${NAS_GID}
      device: "//${NAS_IP}/tv"
  cifs-files-tv2:
    driver: local
    driver_opts:
      type: cifs
      o: username=${NAS_USER},password=${NAS_PASS},uid=${NAS_UID},gid=${NAS_GID}
      device: "//${NAS_IP}/sickchill/tv_dl"
  cifs-files-sd:
    driver: local
    driver_opts:
      type: cifs
      o: username=${NAS_USER},password=${NAS_PASS},uid=${NAS_UID},gid=${NAS_GID}
      device: "//${NAS_IP}/sd"
  cifs-files-hd:
    driver: local
    driver_opts:
      type: cifs
      o: username=${NAS_USER},password=${NAS_PASS},uid=${NAS_UID},gid=${NAS_GID}
      device: "//${NAS_IP}/hd"
  cifs-files-misc-subgen-models:
    driver: local
    driver_opts:
      type: cifs
      o: username=${NAS_USER},password=${NAS_PASS},uid=${NAS_UID},gid=${NAS_GID}
      device: "//${NAS_IP}/misc/subgen/models"

